var add =2 +2;
console.log("add equal to",add);
var subtract =2 - 2;
console.log("subtract equal to",subtract);
var multiply =2 * 2;
console.log("multiply  equal to",multiply);
var divide =2 /2;
console.log("divide equal to",divide);
var remainder =2 %2;
console.log("remainder equal to",remainder);
var power =2 **2;
console.log("power equal to",power);

var a=2;
var b=a;
console.log("a equal to",a);

var a=2;
console.log("a equal ",a==2);

var a=2;
var b=2;
console.log("equals ",a==b);
var a=2;
var b="2";
console.log("type of a",typeof(a),"type of b",typeof(b));
console.log("equals ",a==b);
var a=2;
var b="2";
console.log("equals ",a===b);
var a=2;
var b=4;
console.log("equals ",a<b);
var a=2;
var b=4;
console.log("equals ",a>b);
var a=2;
var b=4;
console.log("equals ",a<=b);
var a=2;
var b=4;
console.log("equals ",a>=b);
var a=2;
var b=4;
console.log("equals ",a!=b);
var a=2;
a++;
console.log(a);
var a=2;
a--;
console.log(a);
var a=2;
++a;
console.log(a);
var a=2;
--a;
console.log(a);
var a=5;
console.log(a++);
console.log(a)

